export enum WidgetList {
  AboutDao = 'AboutDao',
  ExpectedEvents = 'ExpectedEvents',
  Calendar = 'Calendar',
  Reviews = 'Reviews',
  Projects = 'Projects',
  Twitter = 'Twitter',
  RecentActivity = 'RecentActivity',
  ContributorProfiles = 'ContributorProfiles',
  MonthlyPlan = 'MonthlyPlan',
  TotalBalance = 'TotalBalance',
  Portfolio = 'Portfolio',
  Notifications = 'Notifications',
  Discussions = 'Discussions',
  Transactions = 'Transactions',
  Chart = 'Chart',
  Proposals = 'Proposals',
  Blogs = 'Blogs',
  Tokens = 'Tokens',
}
