export enum Context {
  DAO = 'DAO',
  PROJECT = 'PROJECT',
  TASK = 'TASK',
  JOB = 'JOB',
  USER = 'USER',
}

export enum Visibility {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}

export declare enum ActionType {
  PROJECT_CREATED = 'projectCreated',
  PROJECT_UPDATED = 'projectUpdated',
  TASK_CREATED = 'taskCreated',
  TASK_UPDATED = 'taskUpdated',
  TASK_IN_REVIEW = 'taskInReview',
  TASK_COMPLETED = 'taskCompleted',
  CONTRIBUTOR_ADDED_TO_TASK = 'contributorAddedToTask',
  CONTRIBUTOR_ADDED_TO_PROJECT = 'contributorAddedToProject',
  REVIEW_ADDED = 'reviewAdded',
  SNAPSHOT_ADDED = 'snapshotAdded',
  SNAPSHOT_UPDATED = 'snapshotUpdated',
  GITHUB_ADDED = 'githubAdded',
  GITHUB_UPDATED = 'githubUpdated',
  GCAL_ADDED = 'gcalAdded',
  GCAL_UPDATED = 'gcalUpdated',
  GCAL_EVENT_CREATED = 'gcalEventCreated',
  TWITTER_ADDED = 'twitterAdded',
  TWITTER_UPDATED = 'twitterUpdated',
  BLOG_ADDED = 'blogAdded',
  BLOG_UPDATED = 'blogUpdated',
  DISCUSSION_ADDED = 'discussionAdded',
  DISCUSSION_UPDATED = 'discussionUpdated',
  DAO_ACCESS_UPDATED = 'daoAccessUpdated',
  ACCESS_UPDATED = 'accessUpdated',
  PROJECT_COMMON_ACCESS_UPDATED = 'projectCommonAccessUpdated',
  TASK_COMMON_ACCESS_UPDATED = 'taskCommonAccessUpdated',
  VIEW_COMMON_ACCESS_UPDATED = 'viewCommonAccessUpdated',
  CONNECTION_SENT = 'connectionSent',
  CONNECTION_ACCEPTED = 'connectionAccepted',
  CONNECTION_REJECTED = 'connectionRejected',
}
